# Generated by Django 5.0.1 on 2026-01-20 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Regla')),
                ('rule_type', models.CharField(choices=[('PER_AMOUNT', 'Puntos por monto gastado'), ('FIXED_MIN_ORDER', 'Puntos fijos por compra mínima')], default='PER_AMOUNT', max_length=20, verbose_name='Tipo de Regla')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo para que aplique esta regla.', max_digits=10, verbose_name='Valor Mínimo de Compra')),
                ('points_to_award', models.IntegerField(help_text='Puntos que se ganan por cada unidad de monto o fijos.', verbose_name='Puntos a Otorgar')),
                ('amount_step', models.DecimalField(blank=True, decimal_places=2, help_text='Ej: Cada $10. Si es nulo se asume el total.', max_digits=10, null=True, verbose_name="Monto Paso (para 'Por monto')")),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Regla de Obtención de Puntos',
                'verbose_name_plural': 'Reglas de Obtención de Puntos',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Activar o desactivar todo el sistema de fidelidad.', verbose_name='Programa Activo')),
                ('name', models.CharField(default='Programa de Recompensas', max_length=100, verbose_name='Nombre del Programa')),
            ],
            options={
                'verbose_name': 'Configuración del Programa',
                'verbose_name_plural': 'Configuración del Programa',
            },
        ),
        migrations.CreateModel(
            name='RewardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Recompensa')),
                ('points_cost', models.IntegerField(help_text='Puntos necesarios para canjear o activar esta recompensa.', verbose_name='Costo en Puntos')),
                ('reward_type', models.CharField(choices=[('FIXED_AMOUNT', 'Descuento Monto Fijo'), ('PERCENTAGE', 'Descuento Porcentaje')], default='FIXED_AMOUNT', max_length=20, verbose_name='Tipo de Recompensa')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Monto en $ o Porcentaje (0-100).', max_digits=10, verbose_name='Valor del Descuento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('auto_redeem_threshold', models.BooleanField(default=False, help_text='Si es True, se genera el cupón automáticamente al llegar a los puntos.', verbose_name='Canje Automático')),
            ],
            options={
                'verbose_name': 'Regla de Recompensa (Cupón)',
                'verbose_name_plural': 'Reglas de Recompensas',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_balance', models.IntegerField(default=0, verbose_name='Puntos Actuales')),
                ('total_points_earned', models.IntegerField(default=0, verbose_name='Total Puntos Ganados Histórico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cuenta de Fidelidad',
                'verbose_name_plural': 'Cuentas de Fidelidad',
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARN', 'Ganancia por Compra'), ('REDEEM', 'Canje de Recompensa'), ('ADJUSTMENT', 'Ajuste Manual'), ('EXPIRATION', 'Expiración'), ('REFUND', 'Reembolso/Devolución')], max_length=20)),
                ('points', models.IntegerField(help_text='Positivo o negativo', verbose_name='Puntos')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('related_order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Orden Relacionada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyaccount', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Transacción de Puntos',
                'verbose_name_plural': 'Transacciones de Puntos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('is_used', models.BooleanField(default=False, verbose_name='Usado')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Uso')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_coupons', to='customers.customer')),
                ('reward_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty.rewardrule', verbose_name='Regla de Origen')),
            ],
            options={
                'verbose_name': 'Cupón de Usuario',
                'verbose_name_plural': 'Cupones de Usuario',
            },
        ),
    ]
