# Generated by Django 5.0.1 on 2026-01-21 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningRuleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Tipo')),
                ('code', models.SlugField(unique=True, verbose_name='Código Interno')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Regla de Obtención',
                'verbose_name_plural': 'Tipos de Reglas de Obtención',
            },
        ),
        migrations.AlterField(
            model_name='earningrule',
            name='rule_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loyalty.earningruletype', verbose_name='Tipo de Regla'),
        ),
    ]

