# Generated by Django 5.0.1 on 2026-01-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_earningruletype_alter_earningrule_rule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningrule',
            name='order_source',
            field=models.CharField(choices=[('ALL', 'Todos los Canales'), ('WEB', 'Web / Delivery'), ('POS', 'Local / POS')], default='ALL', help_text='Aplica esta regla solo a órdenes de este canal.', max_length=10, verbose_name='Canal de Venta'),
        ),
    ]
