# Generated by Django 5.0.1 on 2026-01-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_earningrule_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardrule',
            name='is_birthday_reward',
            field=models.BooleanField(default=False, help_text='Si es True, este cupón se habilita gratis el día del cumpleaños del cliente.', verbose_name='Es regalo de cumpleaños'),
        ),
    ]
