# Generated by Django 5.0.1 on 2026-01-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('luxe.view_menu', 'Ver menú luxe'), ('luxe.manage_menu', 'Gestionar menú luxe'), ('luxe.view_orders', 'Ver pedidos luxe'), ('luxe.manage_orders', 'Gestionar pedidos luxe'), ('luxe.view_reports', 'Ver reportes luxe'), ('restaurant.view_menu', 'Ver menú restaurante'), ('restaurant.manage_menu', 'Gestionar menú restaurante'), ('restaurant.view_tables', 'Ver mesas'), ('restaurant.manage_tables', 'Gestionar mesas'), ('restaurant.view_orders', 'Ver pedidos restaurante'), ('restaurant.manage_orders', 'Gestionar pedidos restaurante'), ('restaurant.view_reports', 'Ver reportes restaurante'), ('reporting.view_all', 'Ver todos los reportes'), ('reporting.view_luxe', 'Ver reportes luxe'), ('reporting.view_restaurant', 'Ver reportes restaurante'), ('reporting.export', 'Exportar reportes')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SUPER_ADMIN', 'Super Administrador'), ('ADMIN_LUXE', 'Administrador Luxe'), ('ADMIN_RESTAURANT', 'Administrador Restaurante'), ('ADMIN_HOTEL', 'Administrador Hotel'), ('ADMIN_POOL', 'Administrador Piscinas'), ('CASHIER', 'Cajero'), ('COOK', 'Cocinero'), ('WAITER', 'Mesero'), ('RECEPTIONIST', 'Recepcionista'), ('CUSTOMER', 'Cliente')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
    ]
