# Generated by Django 5.0.1 on 2026-01-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial_payment_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Número de Pago'),
        ),
    ]
