# Generated by Django 5.0.1 on 2026-02-03 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_unit_cost'),
        ('payments', '0004_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='sri_code',
            field=models.CharField(default='01', help_text='01=Efectivo, 19=Tarjeta Crédito, 20=Otros con SF, 07=Consumidor Final', max_length=10, verbose_name='Código SRI'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Orden'),
        ),
    ]
