# Generated by Django 5.0.1 on 2026-01-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='identification_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
