# Generated by Django 5.0.1 on 2026-01-25 16:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0009_orderitem_unit_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRIConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_url', models.URLField(default='https://apivendo.fronteratech.ec/api/sri/documents/create_and_process_invoice_complete/', verbose_name='URL API Facturación')),
                ('auth_token', models.CharField(help_text='Token proporcionado por FronteraTech (ej: vsr_...)', max_length=255, verbose_name='Token VSR / Auth Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Integración Activa')),
                ('environment', models.CharField(choices=[('TEST', 'Pruebas'), ('PRODUCTION', 'Producción')], default='TEST', max_length=20, verbose_name='Ambiente')),
                ('company_id', models.IntegerField(blank=True, help_text='Requerido solo si no se usa un Token VSR que autodetecta la empresa', null=True, verbose_name='ID de Empresa (API)')),
                ('default_vat_code', models.CharField(default='2', help_text='2=12%, 3=14%, 4=15%, 5=5%', max_length=5, verbose_name='Código IVA Default')),
                ('auto_invoice', models.BooleanField(default=False, help_text='Emitir factura automáticamente al completar una orden', verbose_name='Facturar Automáticamente')),
            ],
            options={
                'verbose_name': 'Configuración SRI',
                'verbose_name_plural': 'Configuración SRI',
            },
        ),
        migrations.CreateModel(
            name='SRIDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('invoice', 'Factura'), ('credit_note', 'Nota de Crédito'), ('debit_note', 'Nota de Débito'), ('remission_guide', 'Guía de Remisión')], default='invoice', max_length=20)),
                ('external_id', models.IntegerField(blank=True, null=True, verbose_name='ID Externo (API)')),
                ('sri_number', models.CharField(blank=True, help_text='001-001-000000001', max_length=50, verbose_name='Número de Documento')),
                ('access_key', models.CharField(blank=True, max_length=49, verbose_name='Clave de Acceso')),
                ('authorization_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Autorización')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('GENERATED', 'XML Generado'), ('SIGNED', 'Firmado'), ('SENT', 'Enviado'), ('AUTHORIZED', 'Autorizado'), ('REJECTED', 'Rechazado'), ('FAILED', 'Fallido')], default='DRAFT', max_length=20)),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_response', models.JSONField(blank=True, default=dict)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sri_document', to='orders.order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Documento Electrónico',
                'verbose_name_plural': 'Documentos Electrónicos',
                'ordering': ['-created_at'],
            },
        ),
    ]
