# Generated by Django 5.0.1 on 2026-01-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('in_store', 'En Tienda'), ('pickup', 'Recogida'), ('delivery', 'Envío')], default='in_store', max_length=20, verbose_name='Tipo de Orden'),
        ),
    ]


