# Generated by Django 5.0.1 on 2026-01-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_identification',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Identificación (Snapshot)'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Cliente (Snapshot)'),
        ),
    ]


