# Generated by Django 5.0.1 on 2026-01-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_customer_identification_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Descuento'),
        ),
    ]
