# Generated by Django 5.0.1 on 2026-01-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_clean_orphan_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('pos', 'POS / Caja')], default='pos', max_length=10, verbose_name='Origen'),
        ),
    ]
