# Generated by Django 5.0.1 on 2026-01-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Unitario (Histórico)'),
        ),
    ]
