# Generated by Django 5.0.1 on 2026-01-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accounting_cost_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cuenta Costos (Venta)'),
        ),
        migrations.AddField(
            model_name='product',
            name='accounting_inventory_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cuenta Inventario (Activo)'),
        ),
        migrations.AddField(
            model_name='product',
            name='accounting_sales_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cuenta Ventas (Ingreso)'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Actual'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Última Compra'),
        ),
        migrations.AddField(
            model_name='product',
            name='line',
            field=models.CharField(blank=True, max_length=100, verbose_name='Línea'),
        ),
        migrations.AddField(
            model_name='product',
            name='subgroup',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subgrupo'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='IVA %'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_measure',
            field=models.CharField(default='Unidad', max_length=50, verbose_name='Unidad de Medida'),
        ),
    ]
