# Generated by Django 5.0.1 on 2026-01-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_alter_printjob_job_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='printer_type',
            field=models.CharField(choices=[('thermal', 'Térmica (Tickets)'), ('label', 'Etiquetas (TSPL)'), ('laser', 'Láser (Facturas)'), ('matrix', 'Matriz de Puntos')], default='thermal', max_length=20, verbose_name='Tipo de Impresora'),
        ),
    ]

