# Generated by Django 5.0.1 on 2026-02-02 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_alter_printer_printer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='label_gap',
            field=models.IntegerField(default=0, help_text='Espacio entre etiquetas (usualmente 2mm, o 0mm para continuo)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Separación/Gap (mm)'),
        ),
        migrations.AddField(
            model_name='printer',
            name='label_height',
            field=models.IntegerField(default=27, help_text='Solo para etiquetas (default 27)', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(150)], verbose_name='Alto Etiqueta (mm)'),
        ),
    ]
