# Generated by Django 5.0.1 on 2026-02-02 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_rename_tables_menu_to_inventario'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='inventario__is_acti_234eee_idx',
            old_name='menu_catego_is_acti_afc8ab_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='inventario__slug_01e07f_idx',
            old_name='menu_catego_slug_6d0e16_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventario__categor_5fa7cd_idx',
            old_name='menu_produc_categor_5ce543_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventario__is_feat_6da153_idx',
            old_name='menu_produc_is_feat_beb8a3_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventario__slug_b6ac16_idx',
            old_name='menu_produc_slug_67bd16_idx',
        ),
    ]
