# Generated by Django 5.0.1 on 2026-02-20 02:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('hex_code', models.CharField(blank=True, help_text='Ej: #FF0000 para rojo', max_length=7, null=True, verbose_name='Código Hexadecimal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Stock')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU de Variante')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Específico (Opcional)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventario.color', verbose_name='Color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventario.product', verbose_name='Producto')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventario.size', verbose_name='Talla')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
