# Generated by Django 5.0.1 on 2026-02-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_color_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='Ej: S, M, L, XL', max_length=200, null=True, verbose_name='Tallas Disponibles'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
    ]
