# Generated by Django 5.0.1 on 2026-01-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaytapiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='', help_text='ID del producto proporcionado por Maytapi', max_length=255, verbose_name='Product ID')),
                ('token', models.CharField(default='', help_text='Token de acceso a la API', max_length=255, verbose_name='Token')),
                ('api_url', models.URLField(default='https://api.maytapi.com/api/', help_text='Endpoint base de la API de Maytapi', max_length=500, verbose_name='API URL')),
                ('phone_id', models.CharField(blank=True, help_text='ID del teléfono configurado', max_length=100, null=True, verbose_name='Phone ID')),
                ('is_active', models.BooleanField(default=True, help_text='Activar o desactivar el servicio de WhatsApp', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Maytapi',
                'verbose_name_plural': 'Configuraciones Maytapi',
            },
        ),
    ]

