# Generated by Django 5.0.1 on 2026-01-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Automatización Activa')),
                ('schedule_time', models.TimeField(default='09:00', verbose_name='Hora de Envío Diario')),
                ('session_name', models.CharField(default='luxe_session', max_length=50, verbose_name='Nombre de Sesión (WPPConnect)')),
                ('phone_number_sender', models.CharField(default='default', help_text='Referencia del número emisor', max_length=20)),
                ('birthday_message_template', models.TextField(default='🎉 ¡Feliz Cumpleaños {first_name}! 🎂\nEn Luxe queremos celebrar contigo.\n🎁 Tienes un 10% DE DESCUENTO en tu próxima compra.\n¡Te esperamos!', help_text='Usa {first_name}, {last_name} para personalizar.', verbose_name='Plantilla de Mensaje de Cumpleaños')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Última Ejecución')),
                ('status_log', models.TextField(blank=True, verbose_name='Log de Estado')),
            ],
            options={
                'verbose_name': 'Configuración WhatsApp',
                'verbose_name_plural': 'Configuraciones WhatsApp',
            },
        ),
    ]
