# Generated by Django 5.0.1 on 2026-01-22 01:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('message_type', models.CharField(choices=[('test', 'Mensaje de Prueba'), ('birthday', 'Cumpleaños'), ('promo', 'Promoción'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Fallido'), ('pending', 'Pendiente')], default='sent', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Cliente')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Envío')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error (si hubo)')),
            ],
            options={
                'verbose_name': 'Historial de Mensaje',
                'verbose_name_plural': 'Historial de Mensajes',
                'ordering': ['-sent_at'],
            },
        ),
    ]
