# Generated by Django 5.0.1 on 2026-01-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maytapiconfig',
            name='birthday_message_template',
            field=models.TextField(default='¡Feliz cumpleaños {name}! 🎉 En Luxe queremos celebrar contigo. Visítanos hoy y recibe un regalo especial de la casa. ¡Te esperamos!', help_text='Usa {name} para insertar el nombre del cliente.', verbose_name='Plantilla Mensaje Cumpleaños'),
        ),
        migrations.AddField(
            model_name='maytapiconfig',
            name='schedule_time',
            field=models.TimeField(default='09:00', help_text='Hora diaria para enviar felicitaciones de cumpleaños', verbose_name='Hora de Envío (Cron)'),
        ),
    ]

