# Generated by Django 5.0.1 on 2026-01-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_maytapiconfig_birthday_message_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('message_type', models.CharField(choices=[('TEST', 'Prueba'), ('BIRTHDAY', 'Cumpleaños'), ('OTHER', 'Otro')], default='OTHER', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(max_length=50, verbose_name='Estado')),
                ('response_data', models.TextField(blank=True, null=True, verbose_name='Respuesta API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de WhatsApp',
                'verbose_name_plural': 'Logs de WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
